export const MESSAGE_CODES = {
  // ─── Auth ──────────────────────────────────────────────────────────────────
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  PHARMACY_SELECTED: 'PHARMACY_SELECTED',
  PHARMACY_NOT_SELECTED: 'PHARMACY_NOT_SELECTED',
  ME_FETCHED: 'ME_FETCHED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // ─── Common errors ─────────────────────────────────────────────────────────
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  PHARMACY_CONTEXT_REQUIRED: 'PHARMACY_CONTEXT_REQUIRED',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // ─── Medicines ─────────────────────────────────────────────────────────────
  MEDICINES_FETCHED: 'MEDICINES_FETCHED',
  MEDICINE_FETCHED: 'MEDICINE_FETCHED',
  MEDICINE_CREATED: 'MEDICINE_CREATED',
  MEDICINE_UPDATED: 'MEDICINE_UPDATED',
  MEDICINE_DELETED: 'MEDICINE_DELETED',
  MEDICINE_NOT_FOUND: 'MEDICINE_NOT_FOUND',
  MEDICINE_ALREADY_EXISTS: 'MEDICINE_ALREADY_EXISTS',

  // ─── Distributors ──────────────────────────────────────────────────────────
  DISTRIBUTORS_FETCHED: 'DISTRIBUTORS_FETCHED',
  DISTRIBUTOR_FETCHED: 'DISTRIBUTOR_FETCHED',
  DISTRIBUTOR_CREATED: 'DISTRIBUTOR_CREATED',
  DISTRIBUTOR_UPDATED: 'DISTRIBUTOR_UPDATED',
  DISTRIBUTOR_DELETED: 'DISTRIBUTOR_DELETED',
  DISTRIBUTOR_NOT_FOUND: 'DISTRIBUTOR_NOT_FOUND',

  // ─── Customers ─────────────────────────────────────────────────────────────
  CUSTOMERS_FETCHED: 'CUSTOMERS_FETCHED',
  CUSTOMER_FETCHED: 'CUSTOMER_FETCHED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  // ─── Medicine shapes ───────────────────────────────────────────────────────
  MEDICINE_SHAPES_FETCHED: 'MEDICINE_SHAPES_FETCHED',
  MEDICINE_SHAPE_FETCHED: 'MEDICINE_SHAPE_FETCHED',
  MEDICINE_SHAPE_CREATED: 'MEDICINE_SHAPE_CREATED',
  MEDICINE_SHAPE_UPDATED: 'MEDICINE_SHAPE_UPDATED',
  MEDICINE_SHAPE_DELETED: 'MEDICINE_SHAPE_DELETED',
  MEDICINE_SHAPE_NOT_FOUND: 'MEDICINE_SHAPE_NOT_FOUND',

  // ─── Medicine types ────────────────────────────────────────────────────────
  MEDICINE_TYPES_FETCHED: 'MEDICINE_TYPES_FETCHED',
  MEDICINE_TYPE_FETCHED: 'MEDICINE_TYPE_FETCHED',
  MEDICINE_TYPE_CREATED: 'MEDICINE_TYPE_CREATED',
  MEDICINE_TYPE_UPDATED: 'MEDICINE_TYPE_UPDATED',
  MEDICINE_TYPE_DELETED: 'MEDICINE_TYPE_DELETED',
  MEDICINE_TYPE_NOT_FOUND: 'MEDICINE_TYPE_NOT_FOUND',

  // ─── Medicine classes ──────────────────────────────────────────────────────
  MEDICINE_CLASSES_FETCHED: 'MEDICINE_CLASSES_FETCHED',
  MEDICINE_CLASS_FETCHED: 'MEDICINE_CLASS_FETCHED',
  MEDICINE_CLASS_CREATED: 'MEDICINE_CLASS_CREATED',
  MEDICINE_CLASS_UPDATED: 'MEDICINE_CLASS_UPDATED',
  MEDICINE_CLASS_DELETED: 'MEDICINE_CLASS_DELETED',
  MEDICINE_CLASS_NOT_FOUND: 'MEDICINE_CLASS_NOT_FOUND',

  // ─── Purchase orders ───────────────────────────────────────────────────────
  PURCHASE_ORDERS_FETCHED: 'PURCHASE_ORDERS_FETCHED',
  PURCHASE_ORDER_FETCHED: 'PURCHASE_ORDER_FETCHED',
  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  PURCHASE_ORDER_UPDATED: 'PURCHASE_ORDER_UPDATED',
  PURCHASE_ORDER_DELETED: 'PURCHASE_ORDER_DELETED',
  PURCHASE_ORDER_PRINT_FETCHED: 'PURCHASE_ORDER_PRINT_FETCHED',
  PURCHASE_ORDER_SUBMITTED: 'PURCHASE_ORDER_SUBMITTED',
  PURCHASE_ORDER_COMPLETED: 'PURCHASE_ORDER_COMPLETED',
  PURCHASE_ORDER_CANCELLED: 'PURCHASE_ORDER_CANCELLED',
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_NOT_FOUND',

  // ─── Invoices ──────────────────────────────────────────────────────────────
  INVOICES_FETCHED: 'INVOICES_FETCHED',
  INVOICE_FETCHED: 'INVOICE_FETCHED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',

  // ─── Stock ─────────────────────────────────────────────────────────────────
  STOCKS_FETCHED: 'STOCKS_FETCHED',
  STOCK_FETCHED: 'STOCK_FETCHED',
  STOCK_DETAIL_FETCHED: 'STOCK_DETAIL_FETCHED',
  STOCK_MOVEMENTS_FETCHED: 'STOCK_MOVEMENTS_FETCHED',
  STOCK_ALERTS_FETCHED: 'STOCK_ALERTS_FETCHED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  STOCK_PRICE_UPDATED: 'STOCK_PRICE_UPDATED',
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_UPDATED: 'STOCK_UPDATED',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',

  // ─── Sales ─────────────────────────────────────────────────────────────────
  SALES_FETCHED: 'SALES_FETCHED',
  SALE_FETCHED: 'SALE_FETCHED',
  SALE_CREATED: 'SALE_CREATED',
  SALE_CANCELLED: 'SALE_CANCELLED',
  SALE_REFUNDED: 'SALE_REFUNDED',
  SALE_PAYMENT_ADDED: 'SALE_PAYMENT_ADDED',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',

  // ─── Stock returns ─────────────────────────────────────────────────────────
  STOCK_RETURNS_FETCHED: 'STOCK_RETURNS_FETCHED',
  STOCK_RETURN_FETCHED: 'STOCK_RETURN_FETCHED',
  STOCK_RETURN_CREATED: 'STOCK_RETURN_CREATED',
  STOCK_RETURN_UPDATED: 'STOCK_RETURN_UPDATED',
  STOCK_RETURN_DELETED: 'STOCK_RETURN_DELETED',
  STOCK_RETURN_COMPLETED: 'STOCK_RETURN_COMPLETED',
  STOCK_RETURN_CANCELLED: 'STOCK_RETURN_CANCELLED',
  STOCK_RETURN_NOT_FOUND: 'STOCK_RETURN_NOT_FOUND',

  // ─── Stock disposals ───────────────────────────────────────────────────────
  STOCK_DISPOSALS_FETCHED: 'STOCK_DISPOSALS_FETCHED',
  STOCK_DISPOSAL_FETCHED: 'STOCK_DISPOSAL_FETCHED',
  STOCK_DISPOSAL_CREATED: 'STOCK_DISPOSAL_CREATED',
  STOCK_DISPOSAL_UPDATED: 'STOCK_DISPOSAL_UPDATED',
  STOCK_DISPOSAL_DELETED: 'STOCK_DISPOSAL_DELETED',
  STOCK_DISPOSAL_SUBMITTED: 'STOCK_DISPOSAL_SUBMITTED',
  STOCK_DISPOSAL_COMPLETED: 'STOCK_DISPOSAL_COMPLETED',
  STOCK_DISPOSAL_CANCELLED: 'STOCK_DISPOSAL_CANCELLED',
  STOCK_DISPOSAL_NOT_FOUND: 'STOCK_DISPOSAL_NOT_FOUND',

  // ─── Permissions ───────────────────────────────────────────────────────────
  PERMISSIONS_FETCHED: 'PERMISSIONS_FETCHED',
  PERMISSION_FETCHED: 'PERMISSION_FETCHED',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',

  // ─── Roles ─────────────────────────────────────────────────────────────────
  ROLES_FETCHED: 'ROLES_FETCHED',
  ROLE_FETCHED: 'ROLE_FETCHED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_PERMISSIONS_UPDATED: 'ROLE_PERMISSIONS_UPDATED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_ALREADY_EXISTS: 'ROLE_NAME_ALREADY_EXISTS',
  ROLE_IN_USE: 'ROLE_IN_USE',
  ONE_OR_MORE_PERMISSIONS_NOT_FOUND: 'ONE_OR_MORE_PERMISSIONS_NOT_FOUND',
  ONLY_PLATFORM_ADMIN_CAN_CREATE_GLOBAL_ROLE: 'ONLY_PLATFORM_ADMIN_CAN_CREATE_GLOBAL_ROLE',
  ONLY_PLATFORM_ADMIN_CAN_UPDATE_GLOBAL_ROLE: 'ONLY_PLATFORM_ADMIN_CAN_UPDATE_GLOBAL_ROLE',
  ONLY_PLATFORM_ADMIN_CAN_DELETE_GLOBAL_ROLE: 'ONLY_PLATFORM_ADMIN_CAN_DELETE_GLOBAL_ROLE',
  ONLY_PLATFORM_ADMIN_CAN_MANAGE_GLOBAL_ROLE_PERMISSIONS: 'ONLY_PLATFORM_ADMIN_CAN_MANAGE_GLOBAL_ROLE_PERMISSIONS',

  // ─── Me ────────────────────────────────────────────────────────────────────
  ME_UPDATED: 'ME_UPDATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  NEW_PASSWORD_MUST_BE_DIFFERENT: 'NEW_PASSWORD_MUST_BE_DIFFERENT',

  // ─── Users ─────────────────────────────────────────────────────────────────
  USERS_FETCHED: 'USERS_FETCHED',
  USER_FETCHED: 'USER_FETCHED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_HAS_ACTIVE_PLACEMENTS: 'USER_HAS_ACTIVE_PLACEMENTS',
  CANNOT_DELETE_YOURSELF: 'CANNOT_DELETE_YOURSELF',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  DEFAULT_PASSWORD_NOT_CONFIGURED: 'DEFAULT_PASSWORD_NOT_CONFIGURED',

  // ─── Placements ────────────────────────────────────────────────────────────
  PLACEMENTS_FETCHED: 'PLACEMENTS_FETCHED',
  PLACEMENT_FETCHED: 'PLACEMENT_FETCHED',
  PLACEMENT_CREATED: 'PLACEMENT_CREATED',
  PLACEMENT_UPDATED: 'PLACEMENT_UPDATED',
  PLACEMENT_DELETED: 'PLACEMENT_DELETED',
  PLACEMENT_NOT_FOUND: 'PLACEMENT_NOT_FOUND',
  MAX_PLACEMENTS_REACHED: 'MAX_PLACEMENTS_REACHED',
  USER_ALREADY_PLACED_AT_PHARMACY: 'USER_ALREADY_PLACED_AT_PHARMACY',
  PHARMACY_ALREADY_HAS_SIGN_FULL_USER: 'PHARMACY_ALREADY_HAS_SIGN_FULL_USER',
  PHARMACY_ALREADY_HAS_HEAD_PHARMACIST: 'PHARMACY_ALREADY_HAS_HEAD_PHARMACIST',
  PLACEMENT_DATE_OVERLAP: 'PLACEMENT_DATE_OVERLAP',
  LICENSE_REQUIRED_FOR_ROLE: 'LICENSE_REQUIRED_FOR_ROLE',

  // ─── Licenses ──────────────────────────────────────────────────────────────
  LICENSES_FETCHED: 'LICENSES_FETCHED',
  LICENSE_FETCHED: 'LICENSE_FETCHED',
  LICENSE_CREATED: 'LICENSE_CREATED',
  LICENSE_UPDATED: 'LICENSE_UPDATED',
  LICENSE_DELETED: 'LICENSE_DELETED',
  LICENSE_NOT_FOUND: 'LICENSE_NOT_FOUND',
  LICENSE_NUMBER_ALREADY_EXISTS: 'LICENSE_NUMBER_ALREADY_EXISTS',

  // ─── Business Licenses ─────────────────────────────────────────────────────
  BUSINESS_LICENSES_FETCHED: 'BUSINESS_LICENSES_FETCHED',
  BUSINESS_LICENSE_FETCHED: 'BUSINESS_LICENSE_FETCHED',
  BUSINESS_LICENSE_CREATED: 'BUSINESS_LICENSE_CREATED',
  BUSINESS_LICENSE_UPDATED: 'BUSINESS_LICENSE_UPDATED',
  BUSINESS_LICENSE_DELETED: 'BUSINESS_LICENSE_DELETED',
  BUSINESS_LICENSE_NOT_FOUND: 'BUSINESS_LICENSE_NOT_FOUND',
  BUSINESS_LICENSE_NUMBER_ALREADY_EXISTS: 'BUSINESS_LICENSE_NUMBER_ALREADY_EXISTS',

  // ─── Practice Licenses ──────────────────────────────────────────────────────
  PRACTICE_LICENSES_FETCHED: 'PRACTICE_LICENSES_FETCHED',
  PRACTICE_LICENSE_FETCHED: 'PRACTICE_LICENSE_FETCHED',
  PRACTICE_LICENSE_CREATED: 'PRACTICE_LICENSE_CREATED',
  PRACTICE_LICENSE_UPDATED: 'PRACTICE_LICENSE_UPDATED',
  PRACTICE_LICENSE_DELETED: 'PRACTICE_LICENSE_DELETED',
  PRACTICE_LICENSE_NOT_FOUND: 'PRACTICE_LICENSE_NOT_FOUND',
  PRACTICE_LICENSE_NUMBER_ALREADY_EXISTS: 'PRACTICE_LICENSE_NUMBER_ALREADY_EXISTS',
  PRACTICE_LICENSE_PLACEMENT_NOT_FOUND: 'PRACTICE_LICENSE_PLACEMENT_NOT_FOUND',

  // ─── Pharmacies ────────────────────────────────────────────────────────────
  PHARMACIES_FETCHED: 'PHARMACIES_FETCHED',
  PHARMACY_FETCHED: 'PHARMACY_FETCHED',
  PHARMACY_CREATED: 'PHARMACY_CREATED',
  PHARMACY_UPDATED: 'PHARMACY_UPDATED',
  PHARMACY_DELETED: 'PHARMACY_DELETED',
  PHARMACY_NOT_FOUND: 'PHARMACY_NOT_FOUND',
  PHARMACY_CODE_ALREADY_EXISTS: 'PHARMACY_CODE_ALREADY_EXISTS',
  PHARMACY_PARAMETERS_FETCHED: 'PHARMACY_PARAMETERS_FETCHED',
  PHARMACY_PARAMETERS_UPDATED: 'PHARMACY_PARAMETERS_UPDATED',

} as const;

export type MessageCode = typeof MESSAGE_CODES[keyof typeof MESSAGE_CODES];