// src/constants/messageCodes.ts

export const MESSAGE_CODES = {
  // general
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  PHARMACY_NOT_SELECTED: 'PHARMACY_NOT_SELECTED',

  // auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // medicine shapes
  MEDICINE_SHAPES_FETCHED: 'MEDICINE_SHAPES_FETCHED',
  MEDICINE_SHAPE_FETCHED: 'MEDICINE_SHAPE_FETCHED',
  MEDICINE_SHAPE_CREATED: 'MEDICINE_SHAPE_CREATED',
  MEDICINE_SHAPE_UPDATED: 'MEDICINE_SHAPE_UPDATED',
  MEDICINE_SHAPE_DELETED: 'MEDICINE_SHAPE_DELETED',

  // medicine types
  MEDICINE_TYPES_FETCHED: 'MEDICINE_TYPES_FETCHED',
  MEDICINE_TYPE_FETCHED: 'MEDICINE_TYPE_FETCHED',
  MEDICINE_TYPE_CREATED: 'MEDICINE_TYPE_CREATED',
  MEDICINE_TYPE_UPDATED: 'MEDICINE_TYPE_UPDATED',
  MEDICINE_TYPE_DELETED: 'MEDICINE_TYPE_DELETED',

  // medicine classes
  MEDICINE_CLASSES_FETCHED: 'MEDICINE_CLASSES_FETCHED',
  MEDICINE_CLASS_FETCHED: 'MEDICINE_CLASS_FETCHED',
  MEDICINE_CLASS_CREATED: 'MEDICINE_CLASS_CREATED',
  MEDICINE_CLASS_UPDATED: 'MEDICINE_CLASS_UPDATED',
  MEDICINE_CLASS_DELETED: 'MEDICINE_CLASS_DELETED',

  // medicines
  MEDICINE_FETCHED: 'MEDICINE_FETCHED',
  MEDICINES_FETCHED: 'MEDICINES_FETCHED',
  MEDICINE_CREATED: 'MEDICINE_CREATED',
  MEDICINE_UPDATED: 'MEDICINE_UPDATED',
  MEDICINE_DELETED: 'MEDICINE_DELETED',
  MEDICINE_NOT_FOUND: 'MEDICINE_NOT_FOUND',
  MEDICINE_ALREADY_EXISTS: 'MEDICINE_ALREADY_EXISTS',

  // distributors
  DISTRIBUTOR_FETCHED: 'DISTRIBUTOR_FETCHED',
  DISTRIBUTORS_FETCHED: 'DISTRIBUTORS_FETCHED',
  DISTRIBUTOR_CREATED: 'DISTRIBUTOR_CREATED',
  DISTRIBUTOR_UPDATED: 'DISTRIBUTOR_UPDATED',
  DISTRIBUTOR_DELETED: 'DISTRIBUTOR_DELETED',
  DISTRIBUTOR_NOT_FOUND: 'DISTRIBUTOR_NOT_FOUND',

  // purchase orders
  PURCHASE_ORDERS_FETCHED: 'PURCHASE_ORDERS_FETCHED',
  PURCHASE_ORDER_FETCHED: 'PURCHASE_ORDER_FETCHED',
  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  PURCHASE_ORDER_UPDATED: 'PURCHASE_ORDER_UPDATED',
  PURCHASE_ORDER_SUBMITTED: 'PURCHASE_ORDER_SUBMITTED',
  PURCHASE_ORDER_CANCELLED: 'PURCHASE_ORDER_CANCELLED',
  PURCHASE_ORDER_DELETED: 'PURCHASE_ORDER_DELETED',
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_NOT_FOUND',

  // invoices
  INVOICE_FETCHED: 'INVOICE_FETCHED',
  INVOICES_FETCHED: 'INVOICES_FETCHED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',

  // stock
  STOCKS_FETCHED: 'STOCKS_FETCHED',
  STOCK_FETCHED: 'STOCK_FETCHED',
  STOCK_UPDATED: 'STOCK_UPDATED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  STOCK_PRICE_UPDATED: 'STOCK_PRICE_UPDATED',
  STOCK_MOVEMENTS_FETCHED: 'STOCK_MOVEMENTS_FETCHED',
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',
  // STOCK_RETURN_CREATED: 'STOCK_RETURN_CREATED',
  // STOCK_DISPOSAL_CREATED: 'STOCK_DISPOSAL_CREATED',

  // sales
  SALES_FETCHED: 'SALES_FETCHED',
  SALE_FETCHED: 'SALE_FETCHED',
  SALE_CREATED: 'SALE_CREATED',
  SALE_UPDATED: 'SALE_UPDATED',
  SALE_DELETED: 'SALE_DELETED',
  SALE_CANCELLED: 'SALE_CANCELLED',
  SALE_REFUNDED: 'SALE_REFUNDED',
  SALE_PAYMENT_ADDED: 'SALE_PAYMENT_ADDED',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',

  // customers
  CUSTOMER_FETCHED: 'CUSTOMER_FETCHED',
  CUSTOMERS_FETCHED: 'CUSTOMERS_FETCHED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  // stock returns
  STOCK_RETURNS_FETCHED: 'STOCK_RETURNS_FETCHED',
  STOCK_RETURN_FETCHED: 'STOCK_RETURN_FETCHED',
  STOCK_RETURN_CREATED: 'STOCK_RETURN_CREATED',
  STOCK_RETURN_UPDATED: 'STOCK_RETURN_UPDATED',
  STOCK_RETURN_COMPLETED: 'STOCK_RETURN_COMPLETED',
  STOCK_RETURN_CANCELLED: 'STOCK_RETURN_CANCELLED',
  STOCK_RETURN_DELETED: 'STOCK_RETURN_DELETED',
  STOCK_RETURN_NOT_FOUND: 'STOCK_RETURN_NOT_FOUND',

  // stock disposals
  STOCK_DISPOSALS_FETCHED: 'STOCK_DISPOSALS_FETCHED',
  STOCK_DISPOSAL_FETCHED: 'STOCK_DISPOSAL_FETCHED',
  STOCK_DISPOSAL_CREATED: 'STOCK_DISPOSAL_CREATED',
  STOCK_DISPOSAL_UPDATED: 'STOCK_DISPOSAL_UPDATED',
  STOCK_DISPOSAL_COMPLETED: 'STOCK_DISPOSAL_COMPLETED',
  STOCK_DISPOSAL_CANCELLED: 'STOCK_DISPOSAL_CANCELLED',
  STOCK_DISPOSAL_DELETED: 'STOCK_DISPOSAL_DELETED',
  STOCK_DISPOSAL_NOT_FOUND: 'STOCK_DISPOSAL_NOT_FOUND',
  
} as const

export type MessageCode = typeof MESSAGE_CODES[keyof typeof MESSAGE_CODES]